{{- if and .Values.mongodb.enabled .Values.mongodb.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongodb.name }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "solar-system.mongodb.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.mongodb.persistence.storageClass }}
  storageClassName: {{ .Values.mongodb.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
{{- end }}
